name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  schedule:
    # 00:00 UTC mỗi ngày (khoảng 07:00 sáng giờ Việt Nam)
    - cron: '0 0 * * *'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Run Unit Tests
        run: mvn -B -ntp test

  integration:
    runs-on: ubuntu-latest
    needs: unit # Đảm bảo UT chạy xong và xanh thì mới chạy IT
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      # Dùng failsafe:integration để chỉ chạy các file *IT.java nếu bạn đã chạy test ở job trước
      - name: Run Integration Tests
        run: mvn -B -ntp verify -DskipUnitTests

      - name: Upload JaCoCo report
        if: always() # Luôn upload report kể cả khi test fail để còn biết fail ở đâu
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/ # Thêm dấu / để lấy toàn bộ folder